--- !ruby/object:Jumpstart::Configuration
application_name: FieldConnect
business_name: Letsapp Limited
domain: fg.letsapp.cloud
support_email: support@letsapp.biz
default_from_email: admin@letsapp.biz
business_address: |-
  Smart-Space, Level 4, Core E, Cyberport 3
  100 Cyberport Road, Hong Kong
background_job_processor: async
email_provider: sendgrid
payment_processors:
- stripe
